### ISSUE TITLE
slow shutdown in testing

### ISSUE THREAD

**Issue by danmoorenhs** [awslabs/amazon-sqs-java-messaging-lib#114]
hi there,

we're experiencing very long spring boot shutdown times which makes our automated testing slow and painful - around 20 seconds per listener/session - is there a way we can configure or control/override this behaviour?

these lines from our logs seems to be related..

`{"@timestamp":"2022-08-09T11:57:05.802Z","level":"INFO","service":"ehr-transfer-service","class":"SQSMessageConsumer","line":"229","message":"Shutting down ConsumerPrefetch executor","environment":"local"}

{"@timestamp":"2022-08-09T11:57:06.305Z","level":"INFO","service":"ehr-transfer-service","class":"SQSSession","line":"421","message":"Shutting down SessionCallBackScheduler executor","environment":"local"}`

thanks!

**Comment by seanliu-oss** [comment]
I believe this is caused by the hardcoded 20 seconds WAIT_TIME_SECONDS in ConsumerPrefetch.
https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/c16c185f9e2c67abf3babcad4378b52af8e52a0b/src/main/java/com/amazon/sqs/javamessaging/SQSMessageConsumerPrefetch.java#L65

This should be user configurable for cases like testing.

**Comment by pzygielo** [comment]
- #140
