### ISSUE TITLE
Why is this project owned by awslabs rather than aws and what's the significance?

### ISSUE THREAD

**Issue by neiljbrown** [awslabs/amazon-sqs-java-messaging-lib#17]
What is the significance of this project being owned by the awslabs Github org rather the main [aws org](https://github.com/aws)?

Is there an official statement on how projects hosted in these two different orgs differ, e.g. in terms of the level of Amazon support, maintenance and future development?

It would be useful for this to be clarified to inform Amazon customer decisions on whether 'awslabs' projects are suitable for use in production applications, and what if any risks apply when using the projects.

Thanks.

**Comment by trex-amazon** [comment]
Everything on both the AWS and AWS Labs GitHub organizations is for customer use. The AWS Labs GitHub organization contains sample code, early access, and experimental projects from Amazon Web Services, while the AWS GitHub organization contains more mature software. The level of attention we pay to the AWS Labs repositories is generally expected to be the same as on the AWS GitHub organization, but due to being smaller and earlier in their life cycle, there is less folk working on them. 
 
With regards to future development - the projects in AWS Labs are generally more likely to change their code and/or API (for example the early access projects), and may not have plans for continued development (for example the sample code). If a project has specific risks or production use concerns, it will identify that in its README. Otherwise, you should treat this software in the same way you would any software (reviewing licensing, need for paid support, etc.). 

Raising an issue, like this one, is a great way to give us feedback that we should be considering whether it's time to move a specific project over to the main AWS GitHub organization. This library, in particular, is one that will likely be moved to the AWS GitHub organization in the future.

Resolving, but please feel free to reopen. Apologies for the slowness in our replying,
