### ISSUE TITLE
Add support for MessageSelectors

### ISSUE THREAD

**Issue by lucasweb78** [awslabs/amazon-sqs-java-messaging-lib#4]
amazon-sqs-java-messaging-lib does not currently support MessageSelectors. Attempting to create a Message Selector results in the following error:

```
javax.jms.JMSException : SQSSession does not support MessageSelector. This should be null. [Proxied because : Original exception not deserilizable, ClassNotFoundException]
    at com.amazon.sqs.javamessaging.SQSSession.createConsumer(SQSSession.java:539)
    at org.springframework.jms.core.JmsTemplate.createConsumer(JmsTemplate.java:993)
    at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:722)
    at org.springframework.jms.core.JmsTemplate$10.doInJms(JmsTemplate.java:706)
    at org.springframework.jms.core.JmsTemplate$10.doInJms(JmsTemplate.java:703)
    at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:466)
```

Below is our current deployment environment:
- Wildfly 8.2
- Camel 2.14
- Camel JMS (which in turn uses Spring JMS)
- JMS Providers HornetQ and ActiveMQ

Currently we rely on our JMS providers to support
- JMSPriority
- MessageSelectors
- transacted

**Comment by kuba-aws** [comment]
SQS currently does not support message priorities, transactions nor message selectors. Since this library is a wrapper around SQS, it cannot support features that SQS does not provide.
Resolving this. As SQS gets new features in the future, the library will be enhanced with support for them (example: version 1.0.2 has been released with support for SQS FIFO queues).

**Comment by aholbreich** [comment]
Message selector is usefull feature. Any idea how to select subset of the messages from the queue based on some header? Preferable with Spring

**Comment by kuba-aws** [comment]
Can you provide more details about this use case? If your code needs to access specific subset of messages, consider sending them to a unique queue that contains only those messages.

**Comment by WillerZ** [comment]
@kuba-aws I'm not the OP, and apologies for resurrecting this thread if it's unwelcome, but I can share the motivating example that caused me to find this ticket.

We have used an SQS queue to defer work items that will call an external API to update our CRM with what our customers have been doing. It's good for this to be timely so that if a customer needs to call for support the support staff can see what's recently happened. 

In normal operation the dequeue-and-do-it loop keeps up with the enqueuing of new work and everything is great.

Unfortunately when there's a backlog for any reason we run into the API rate limit on the CRM when clearing the backlog which means the echo of whatever caused the backlog causes problems for longer than we're happy with.

If I had a way to pick all the messages which are for the same user off the queue in one shot I could aggregate the effect of all those messages into one call to the external API, and that would let us clear the backlog very much faster than we are currently able to achieve.

I don't think we want to have the management challenge of creating a queue per customer for this.
