### ISSUE TITLE
Add support for transacted SQS Sessions

### ISSUE THREAD

**Issue by lucasweb78** [awslabs/amazon-sqs-java-messaging-lib#5]
amazon-sqs-java-messaging-lib does not currently support transacted SQS Session. Attempting to create a transacted SQS Session results in the following error:

```
javax.jms.JMSException : SQSSession does not support transacted [Proxied because : Original exception not deserilizable, ClassNotFoundException]
    at com.amazon.sqs.javamessaging.SQSConnection.createSession(SQSConnection.java:173)
    at org.springframework.jms.support.JmsAccessor.createSession(JmsAccessor.java:196)
    at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:457)
    ... 110 more
```

Below is our current deployment environment:

Wildfly 8.2
Camel 2.14
Camel JMS (which in turn uses Spring JMS)
JMS Providers HornetQ and ActiveMQ
Currently we rely on our JMS providers to support

JMSPriority
MessageSelectors
transacted

**Comment by mhurne** [comment]
It seems highly unlikely to me that support for transacted sessions is achievable. Would someone at Amazon mind confirming/denying that?

**Comment by nbrys** [comment]
Please add this!

**Comment by kuba-aws** [comment]
SQS currently does not support message priorities, transactions nor message selectors. Since this library is a wrapper around SQS, it cannot support features that SQS does not provide.
Resolving this. As SQS gets new features in the future, the library will be enhanced with support for them (example: version 1.0.2 has been released with support for SQS FIFO queues).
