### ISSUE TITLE
Add support for JMSPriority header

### ISSUE THREAD

**Issue by lucasweb78** [awslabs/amazon-sqs-java-messaging-lib#6]
amazon-sqs-java-messaging-lib does not currently support the JMSPriority header, it is ignored.

Below is our current deployment environment:

Wildfly 8.2
Camel 2.14
Camel JMS (which in turn uses Spring JMS)
JMS Providers HornetQ and ActiveMQ
Currently we rely on our JMS providers to support

JMSPriority
MessageSelectors
transacted

**Comment by kuba-aws** [comment]
SQS currently does not support message priorities, transactions nor message selectors. Since this library is a wrapper around SQS, it cannot support features that SQS does not provide. 
Resolving this. As SQS gets new features in the future, the library will be enhanced with support for them (example: version 1.0.2 has been released with support for SQS FIFO queues).
