### ISSUE TITLE
Compatibility with AWS SDK 2.x

### ISSUE THREAD

**Issue by Thunderforge** [awslabs/amazon-sqs-java-messaging-lib#78]
[AWS SDK 2.x](https://github.com/aws/aws-sdk-java-v2) has been out for almost a year. Our organization is interested in upgrading to it, but unfortunately, we rely on this library, which at this time only supports AWS SDK 1.x.

I would like to request an upgrade to enable compatibility with AWS SDK 2.x. I imagine this will probably be a separate repository, like the other 2.x libraries.

**Comment by AlexBroadbent** [comment]
I'm in exactly the same boat. Have you found a workaround?

**Comment by ericknet** [comment]
Any plants to add support JMS into SDK v.2?

**Comment by joseslneto** [comment]
Hello guys!

I spent a time and update the code to support SDK v.2 (and i'm using this code in production environment).
I will open a PR to owners analize my modifications.

Any questions, you can text me on pvt.

**Comment by sp00m** [comment]
Just as an FYI, this ticket blocked us going forward because of [EKS supporting 2.10.11+ only](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), so we decided to develop our own abstraction for our Spring WebFlux projects, so that we could connect to SQS from within EKS: https://github.com/qudini/qudini-reactive/tree/master/qudini-reactive-sqs. Very SQS (and WebFlux) focused obviously, and by no means intended to replace https://github.com/awslabs/amazon-sqs-java-messaging-lib, but maybe it can help resolving this issue somehow :)

**Comment by Thunderforge** [comment]
@robin-aws You seem to be the primary committer on this repo. Are you aware of any discussions to make AWS SDK 2.x support a possibility? The work that @sp00m provided seems to indicate it can be done.

**Comment by sfragata** [comment]
What we need to do to get Pieter-Jan PR reviewed and merged?
https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/88

He did a great job to migrate this lib to new aws client version

**Comment by arcturuscom** [comment]
Any updates about this issue ?

**Comment by philmadden83** [comment]
+1

**Comment by dima-starosud** [comment]
+1

**Comment by sorenfalch** [comment]
+42

**Comment by mittalsaurab** [comment]
is there any alternative repo which we can use instead of this for same purpose?

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.0.0
